steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/web-repo/web:$SHORT_SHA',
      '.'
    ]

# Step 2: Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/web-repo/web:$SHORT_SHA'
    ]

# Step 3: Deploy updated image to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: bash
  args:
    - "-c"
    - |
      # Connect to GKE cluster (us-central1 region)
      gcloud container clusters get-credentials demo-autopilot --region us-central1
      
      # Update container image in Deployment
      kubectl set image deployment/web web=us-central1-docker.pkg.dev/$PROJECT_ID/web-repo/web:$SHORT_SHA
options:
  logging: CLOUD_LOGGING_ONLY      
