steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/web-repo/web:$SHORT_SHA',
      '.'
    ]

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/web-repo/web:$SHORT_SHA'
    ]

  # Step 3: Deploy updated image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: bash
    args:
      - "-c"
      - |
        # Connect to the GKE cluster (ensure name/region are correct)
        gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1

        # Update the correct container name inside the deployment
        kubectl set image deployment/web nginx=us-central1-docker.pkg.dev/$PROJECT_ID/web-repo/web:$SHORT_SHA

        # Wait for rollout to finish (optional but useful)
        kubectl rollout status deployment/web --timeout=120s

options:
  logging: CLOUD_LOGGING_ONLY
     
